### ISSUE TITLE
Bug Report - Crash running Munchlax Trees Checker script (Platinum)

### ISSUE THREAD

**Issue by i8sigmapi** [FlagBrew/PKSM-Scripts#44]
**Describe the bug**
Attempting to run the script to determine which trees can give you Munchlax in Platinum version crashes the device.

**To Reproduce**
1. Open Platinum version save
2. Select Scripts
3. Press Y for universal scripts
4. Scroll down to DPPt - Munchlax Trees Checker.c and select it
5. Advance through opening text
6. Crash occurs

**Expected behavior**
The script should run as intended and inform me of which Honey Trees can contain Munchlax without crashing.

**Information about your environment**
 - OS version: Sys 11.16.0-49U, Luma v12.0.1
 - PKSM version: 10.0.0

**Additional context**
Tested on both a dump save and a cartridge save. Happens in both cases.

**Comment by SpiredMoth** [comment]
This is definitely a spooky bug. I have tried 3 different DPPt saves so far, each with different results:
- Pt: Intermittently crashed right after displaying the first pair of trees. When it didn't crash, gibberish was displayed for second pair of trees.
- DP 1: Ran perfectly fine every time.
- DP 2: Crashed every time, right after displaying the first pair of trees.

In hopes that the fix might be this easy, @i8sigmapi can you test something for me?
1. extract this zip to the root of your SD card
[DPPt_Munchlax.zip](https://github.com/FlagBrew/PKSM-Scripts/files/11619160/DPPt_Munchlax.zip)
2. Load your crashing Pt save in PKSM
3. Go to Scripts, press `Y` then `X`
4. Run the listed `DPPt - Munchlax Trees Checker.c` script

If this works, then I'll commit the fix so it'll be in the next PKSM release.

**Comment by i8sigmapi** [comment]
ahh, i'm so sorry i didn't see this until now!

unfortunately, it still crashes. it hasn't ever even displayed the first pair of trees for me.

**Comment by SpiredMoth** [comment]
I should have made this post nearly a month ago (1ba4238) but the script is now fixed.

Instead of being a string issue like I thought, the problem ended up being that IDs were being pulled from the save file as `signed int` but the code was expecting `unsigned int`.

The fixed version of the script will be bundled in the next release of PKSM. If you want to use the script before then, extract the attached zip to the root of your SD card and run the script by doing the following:

1. Open Scripts menu
2. press `Y` to bring up the Universal scripts
3. press `X` to bring up the scripts on your SD card
4. select `DPPt - Munchlax Trees Checker.c`

[DPPt_Munchlax_Checker.zip](https://github.com/FlagBrew/PKSM-Scripts/files/12353684/DPPt_Munchlax_Checker.zip)
